// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlBkDdKgLBnec_OL4p0On7E_xeijmCbU0',
    appId: '1:600076654016:web:4f2ea9227235c5f86ee425',
    messagingSenderId: '600076654016',
    projectId: 'alu-internlink',
    authDomain: 'alu-internlink.firebaseapp.com',
    storageBucket: 'alu-internlink.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAGl2iVi1VC1DaILiLsW_q2e9SIBaHG3A',
    appId: '1:600076654016:android:6d96fdf32ea86b336ee425',
    messagingSenderId: '600076654016',
    projectId: 'alu-internlink',
    storageBucket: 'alu-internlink.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQw4VN9JFRniiwpzKzmyz3xMysiXNADNA',
    appId: '1:600076654016:ios:9594b70a34525d0c6ee425',
    messagingSenderId: '600076654016',
    projectId: 'alu-internlink',
    storageBucket: 'alu-internlink.firebasestorage.app',
    iosBundleId: 'com.example.aluInternlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQw4VN9JFRniiwpzKzmyz3xMysiXNADNA',
    appId: '1:600076654016:ios:9594b70a34525d0c6ee425',
    messagingSenderId: '600076654016',
    projectId: 'alu-internlink',
    storageBucket: 'alu-internlink.firebasestorage.app',
    iosBundleId: 'com.example.aluInternlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlBkDdKgLBnec_OL4p0On7E_xeijmCbU0',
    appId: '1:600076654016:web:292abdc093c24cfe6ee425',
    messagingSenderId: '600076654016',
    projectId: 'alu-internlink',
    authDomain: 'alu-internlink.firebaseapp.com',
    storageBucket: 'alu-internlink.firebasestorage.app',
  );
}
